include:
  - "$DATA_DIR/$ECNAME.yaml"
  - "$DATA_DIR/$CCNAME.yaml"

services:
  stakewise:
    command: src/main.py start
      --vault=$VAULT
      --consensus-endpoints="http://$CCNAME:$CCAPIPORT"
      --execution-endpoints="http://$ECNAME:$ECAPIPORT"
    depends_on:
      - $ECNAME
      - $CCNAME