include:
  - $ECNAME.yaml
  - $CCNAME.yaml

services:
  stakewise:
    image: "europe-west4-docker.pkg.dev/stakewiselabs/public/v3-operator:master"
    container_name: v3-operator
    command: src/main.py start
      --vault=$VAULT
      --consensus-endpoints="http://$CCNAME:$CCPORT"
      --execution-endpoints="http://$ECNAME:$ECPORT"
    volumes:
      - ./stakewise-data:/data
    environment:
      DATA_DIR: /data
    env_file: ./$NAME.env
    depends_on:
      - $ECNAME
      - $CCNAME
  ethdo:
    image: "wealdtech/ethdo"
    env_file: ./$NAME.env
