services:
  stakewise:
    build: .
  geth:
    image: "ethereum/client-go:stable"
    ports:
      - "30303:30303"
  ethdo:
    image: "wealdtech/ethdo"
  nimbus:
    image: "statusim/nimbus-eth2:amd64-latest"
    ports:
      - "9000:9000"
