services:
  geth:
    image: "ethereum/client-go:stable"
    command: --$NETWORK
      --http
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /tmp/jwtsecret
      --http.addr 0.0.0.0
      --http.corsdomain=*
      --http.vhosts=*
      --http.api=web3,eth,net,engine
    env_file:
      - $NAME.env
    volumes:
      - ./tmp:/tmp
      - ./geth-data:/root/.ethereum
    ports:
      # external peering
      - 30303/tcp
      - 30303/udp
      # connection to CC
      - 8551/tcp
      - 8551/udp
      # http API
      - 8545/tcp
      - 8545/udp
